### ISSUE TITLE
Mapping Language  Descriptors  to HLS that aligns with equivalent DASH Roles - Put into next version of doc?

### ISSUE THREAD

**Issue by Yasser-Comcast** [cta-wave/dash-hls#42] opened 2023-02-07 22:04 UTC
The Language descriptor for MPEG-2 TS has a lang and audio_type pair ( with corresponding bsmod equivalents). The audio_type  has been usually a default but is increasingly being used to described the purpose of the audio track and especially accessibility. E.g. are  audio description, enhanced-audio -intelligibility, primary audio, primary commentary.  There are tables that describe a mapping to DASH Roles and Accessibility elements (SCTE 277) , but it is still unclear what are the HLS equivalents to that ( even if it custom metadata). Right now custom metadata can be used for the HLS side of things but this may vary depending on implementation.

We suggest that the CTA DASH-HLS group address topic and see if a mapping to HLS equivalent can exist and be done without having multiple approaches to it.

![Screen Shot 2023-02-01 at 12 47 07 PM](https://user-images.githubusercontent.com/61491458/217377012-f420e881-d8e2-4f87-90ac-710500bc3fb0.png)
![Screen Shot 2023-02-01 at 12 46 56 PM](https://user-images.githubusercontent.com/61491458/217377188-513a54da-cd6d-4d3b-b4d5-cf2b4ecb351d.png)

**Comment by technogeek00** [comment] 2023-02-24 06:50
Closing as duplicate of #40 but image references useful. Adding to second edition.

**Closed by technogeek00** 2023-02-24 06:50 UTC
Labels: use case consideration
